config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  root 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/list', to: 'todos#list'
  get 'todos/:id', to: 'todos#show', as:'todo'
  get 'todos/:id/edit', to: 'todos#edit', as:'todo_edit'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as:'todo_complete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save

    if @todo.save
      redirect_to todos_path
    else
      redirect_to todos_new_path
    end
    
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'todos/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
  <p><%= f.label :description, "Detalle del To Do" %></p>
  <p><%= f.text_area :description %></p>

  <p><%= f.label :completed, "Tarea Terminada" %></p>
  <p><%= f.check_box(:completed) %></p>
  <%= f.submit "Enviar", class: 'btn btn-info'  %>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Index", todos_path %></li>
        <li><%= link_to "Lista", todos_list_path %></li>
        <li><%= link_to "Crear", todos_new_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/todos/edit.html.erb
<%= render 'form' %>

app/views/todos/index.html.erb
<% @todos.each do |todo| %>
  <div class="well">
    <h2><%= todo.description%></h2>
    <p><%= link_to "Mostrar", todo, class: 'btn btn-primary' %>
    <%= link_to "Editar", todo_edit_path(todo), class: 'btn btn-warning' %>
  <%= link_to "Borrar", todo, class: 'btn btn-danger', method: :delete %>
    <%= link_to "¡Listo!", todo_complete_path(todo), class: 'btn btn-success' %></p>
    </div>
  <% end %>

  <h2><%= link_to "Crear To Do", todos_new_path, class: 'btn btn-info' %></h2>

app/views/todos/list.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>¡Listos!</h1>
    <% @todos.each do |todo| %>
      <%if todo.completed == true %>
        <ul>
          <li><%= todo.description %></li>
        </ul>
      <%end%>
    <%end%>

  </div>
    <div class="col-md-6">
      <h1>Por completar...</h1>
    <% @todos.each do |todo| %>
      <%if todo.completed == false %>
        <ul>
          <li><%= todo.description %></li>
        </ul>
      <%end%>
    <%end%>
    </div>
</div>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<h2>Item</h2>
  <%= @todo.description %>
<h2>¿Tarea lista?</h2>
<%if @todo.completed == true %>
    <p><%= "¡Listo!" %></p>
<%end%>

<%if @todo.completed == false %>
    <p><%= "¡Aún falta!" %></p>
<%end%>